# Generated by Django 4.2 on 2023-04-15 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("abbreviation", models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="New character", max_length=255)),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "current_exp",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Current experience",
                    ),
                ),
                ("current_health", models.IntegerField(default=30)),
                ("current_corruption", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BS", "Basic"), ("ADV", "Advanced")],
                        default="BS",
                        max_length=3,
                    ),
                ),
                (
                    "default_type",
                    models.CharField(
                        choices=[
                            ("INT", "Value"),
                            ("ATR", "Attribute"),
                            ("ATR+ATR", "Sum of attributes"),
                        ],
                        default="INT",
                        max_length=10,
                    ),
                ),
                (
                    "default_value",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "default_attribute",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="characters.attribute",
                    ),
                ),
                (
                    "default_attribute_comb",
                    models.ManyToManyField(
                        blank=True,
                        related_name="skill_default_attribute_comb",
                        to="characters.attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_points",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.attribute",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="attributes",
            field=models.ManyToManyField(
                through="characters.CharAttribute", to="characters.attribute"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="skills",
            field=models.ManyToManyField(
                through="characters.CharSkill", to="characters.skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="charskill",
            constraint=models.UniqueConstraint(
                fields=("character", "skill"), name="unique_skill"
            ),
        ),
        migrations.AddConstraint(
            model_name="charattribute",
            constraint=models.UniqueConstraint(
                fields=("character", "attribute"), name="unique_attribute"
            ),
        ),
    ]
