# Generated by Django 4.2 on 2023-04-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_flaw_alter_skill_default_attribute_flawdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="flaw",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="characters.flaw",
            ),
        ),
        migrations.AddConstraint(
            model_name="flawdescription",
            constraint=models.UniqueConstraint(
                fields=("flaw", "intensity"), name="unique_flaw_intensity"
            ),
        ),
    ]
