# Generated by Django 4.2 on 2023-05-04 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaosFactor",
            fields=[
                (
                    "intencity",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FateChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yes_if_equal_or_lower",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "chaos_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mythic.chaosfactor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Probability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, unique=True)),
                (
                    "probabilty_to_chaos_factor",
                    models.ManyToManyField(
                        through="mythic.FateChart", to="mythic.chaosfactor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fatechart",
            name="probability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mythic.probability"
            ),
        ),
        migrations.AddConstraint(
            model_name="fatechart",
            constraint=models.UniqueConstraint(
                fields=("probability", "chaos_factor"),
                name="unique_chaos_factor_probability",
            ),
        ),
    ]
