# Generated by Django 4.2 on 2023-05-04 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="probability",
            old_name="probabilty_to_chaos_factor",
            new_name="probability_to_chaos_factor",
        ),
    ]
