# Generated by Django 4.2 on 2023-05-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "mythic",
            "0002_rename_probabilty_to_chaos_factor_probability_probability_to_chaos_factor",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_chaos_factor",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.PROTECT,
                to="mythic.chaosfactor",
            ),
        ),
    ]
