# Generated by Django 4.2 on 2023-05-04 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0003_game_current_chaos_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatechart",
            name="exceptional_no_if_equal_or_higher",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="fatechart",
            name="exceptional_yes_if_equal_or_lower",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
