# Generated by Django 4.2 on 2023-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0007_meaningtable_meaningtableelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meaningtable",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
