# Generated by Django 4.2 on 2023-05-05 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0008_alter_meaningtable_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meaningtableelement",
            name="id",
        ),
        migrations.AlterField(
            model_name="meaningtableelement",
            name="d100",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="meaningtableelement",
            constraint=models.UniqueConstraint(
                fields=("table", "word"), name="unique_word_in_table"
            ),
        ),
    ]
