# Generated by Django 4.2 on 2023-05-05 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0008_alter_meaningtableelement_d100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meaningtableelement",
            name="d100",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
