# Generated by Django 4.2 on 2023-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0009_alter_meaningtableelement_d100"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meaningtableelement",
            name="d100",
        ),
        migrations.AlterField(
            model_name="meaningtableelement",
            name="word",
            field=models.CharField(max_length=100),
        ),
    ]
