# Generated by Django 4.2 on 2023-05-05 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0009_remove_meaningtableelement_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meaningtableelement",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meaningtableelement",
            name="d100",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
