# Generated by Django 4.2 on 2023-05-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0013_rename_result_sceneadjustmentoption_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="active_scene",
            field=models.ForeignKey(
                limit_choices_to="limit_choices_to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="mythic.scene",
            ),
        ),
    ]
