# Generated by Django 4.2 on 2023-05-10 19:54

from django.db import migrations, models
import django.db.models.deletion
import mythic.models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0014_game_active_scene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="active_scene",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="mythic.scene",
            ),
        ),
    ]
