# Generated by Django 4.2 on 2023-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0016_alter_game_active_scene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meaningtable",
            name="type",
            field=models.CharField(
                choices=[
                    ("ACTION", "Action"),
                    ("DESCRIPTION", "Description"),
                    ("ELEMENT", "Element"),
                ],
                default="ELEMENT",
                max_length=155,
            ),
        ),
    ]
