# Generated by Django 4.2 on 2023-05-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0017_alter_meaningtable_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meaningtableelement",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mythic.meaningtable"
            ),
        ),
    ]
