# Generated by Django 4.2 on 2023-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mythic", "0020_scene_unique_scene_in_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="listnote",
            name="name",
            field=models.CharField(default="halo", max_length=255),
            preserve_default=False,
        ),
    ]
